services:
  odoo:
    image: odoo:17.0
    env_file: .env
    depends_on:
      - postgres
    ports:
      - "127.0.0.1:8069:8069"
    volumes:
      - data:/var/lib/odoo
      # - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
    command: odoo -u all -d odoo_db --dev xml

  postgres:
    image: postgres:13
    env_file: .env
    ports:
      - "5433:5432"
    volumes:
      - db:/var/lib/postgresql/data/pgdata
volumes:
  data:
  db:
  addons: